### ISSUE TITLE
Startup Error 1.18.2 on Docker

### ISSUE THREAD

**Issue by lucaz82** [MKr4zy/Admate#1]
Using the repo's docker-compose.yml

---
Error:
```
[12:51:20] [Worker-Main-5/INFO] [minecraft/LoggerChunkProgressListener]: Preparing spawn area: 15%
[12:51:20] [pool-3-thread-1/INFO] [ne.cr.wy.WhyYouMakeLag/]: Cleaned up caches, removed 0/0 Chunk SpawnManagers and 0/0 block spawn caches. [0]
[12:51:24] [Netty Epoll Server IO #3/INFO] [ne.mi.se.ServerLifecycleHooks/SERVERHOOKS]: Disconnecting Player (server is still starting): Server is still starting! Please wait before reconnecting.
/data/FeedTheBeast/start.sh: line 54:   352 Killed                  "$JAVA" ${1}
```

```
[13:14:27] [Worker-Main-3/INFO] [minecraft/RecipeManager]: Skipping loading recipe bigreactors:turbine/reinforced/computerport_alt as it's serializer returned null
[13:14:27] [Worker-Main-3/INFO] [minecraft/RecipeManager]: Skipping loading recipe delightful:knives/smelting/emerald_emeraldequipment as it's serializer returned null
[13:14:27] [Worker-Main-3/ERROR] [minecraft/RecipeManager]: Parsing error loading recipe create:compat/silentsgems/crushing/sodalite_ore
com.google.gson.JsonSyntaxException: Unknown item 'silentgems:sodalite_ore'
        at net.minecraft.world.item.crafting.ShapedRecipe.m_151280_(ShapedRecipe.java:276) ~[server-1.18.2-20220404.173914-srg.jar%23420!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.shetiphiancore.json:SPC_ShapedRecipe_Invoker,pl:mixin:APP:bookshelf.common.mixins.json:item.crafting.AccessorShapedRecipe,pl:mixin:A}
        at java.util.Optional.orElseThrow(Unknown Source) ~[?:?] {re:mixin}
        at net.minecraft.world.item.crafting.ShapedRecipe.m_151278_(ShapedRecipe.java:275) ~[server-1.18.2-20220404.173914-srg.jar%23420!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.shetiphiancore.json:SPC_ShapedRecipe_Invoker,pl:mixin:APP:bookshelf.common.mixins.json:item.crafting.AccessorShapedRecipe,pl:mixin:A}
        at net.minecraft.world.item.crafting.Ingredient.m_43919_(Ingredient.java:222) ~[server-1.18.2-20220404.173914-srg.jar%23420!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:botania_xplat.mixins.json:AccessorIngredient,pl:mixin:APP:crafttweaker.mixins.json:common.access.item.AccessIngredient,pl:mixin:APP:crafttweaker.mixins.json:common.transform.item.MixinIngredient,pl:mixin:A}
        at net.minecraftforge.common.crafting.VanillaIngredientSerializer.parse(VanillaIngredientSerializer.java:27) ~[forge-1.18.2-40.1.84-universal.jar%23425!/:?] {re:classloading}
        at net.minecraftforge.common.crafting.CraftingHelper.getIngredient(CraftingHelper.java:143) ~[forge-1.18.2-40.1.84-universal.jar%23425!/:?] {re:classloading}
        at net.minecraft.world.item.crafting.Ingredient.m_43917_(Ingredient.java:197) ~[server-1.18.2-20220404.173914-srg.jar%23420!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:botania_xplat.mixins.json:AccessorIngredient,pl:mixin:APP:crafttweaker.mixins.json:common.access.item.AccessIngredient,pl:mixin:APP:crafttweaker.mixins.json:common.transform.item.MixinIngredient,pl:mixin:A}
        at com.simibubi.create.content.contraptions.processing.ProcessingRecipeSerializer.readFromJson(ProcessingRecipeSerializer.java:68) ~[create-1.18.2-0.5.0.e.jar%23123!/:0.5.0.e] {re:classloading}
        at com.simibubi.create.content.contraptions.processing.ProcessingRecipeSerializer.fromJson(ProcessingRecipeSerializer.java:156) ~[create-1.18.2-0.5.0.e.jar%23123!/:0.5.0.e] {re:classloading}
        at com.simibubi.create.content.contraptions.processing.ProcessingRecipeSerializer.m_6729_(ProcessingRecipeSerializer.java:22) ~[create-1.18.2-0.5.0.e.jar%23123!/:0.5.0.e] {re:classloading}
        at net.minecraftforge.common.extensions.IForgeRecipeSerializer.fromJson(IForgeRecipeSerializer.java:23) ~[forge-1.18.2-40.1.84-universal.jar%23425!/:?] {re:classloading,re:mixin}
        at net.minecraft.world.item.crafting.RecipeManager.fromJson(RecipeManager.java:157) ~[server-1.18.2-20220404.173914-srg.jar%23420!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:polymorph.mixins.json:MixinRecipeManager,pl:mixin:APP:mixins.hammerlib.json:RecipeManagerMixin,pl:mixin:APP:botania_xplat.mixins.json:AccessorRecipeManager,pl:mixin:APP:crafttweaker.mixins.json:common.access.recipe.AccessRecipeManager,pl:mixin:APP:farmersdelight.mixins.json:accessor.RecipeManagerAccessor,pl:mixin:A}
        at net.minecraft.world.item.crafting.RecipeManager.m_5787_(RecipeManager.java:67) ~[server-1.18.2-20220404.173914-srg.jar%23420!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:polymorph.mixins.json:MixinRecipeManager,pl:mixin:APP:mixins.hammerlib.json:RecipeManagerMixin,pl:mixin:APP:botania_xplat.mixins.json:AccessorRecipeManager,pl:mixin:APP:crafttweaker.mixins.json:common.access.recipe.AccessRecipeManager,pl:mixin:APP:farmersdelight.mixins.json:accessor.RecipeManagerAccessor,pl:mixin:A}
        at net.minecraft.world.item.crafting.RecipeManager.m_5787_(RecipeManager.java:34) ~[server-1.18.2-20220404.173914-srg.jar%23420!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:polymorph.mixins.json:MixinRecipeManager,pl:mixin:APP:mixins.hammerlib.json:RecipeManagerMixin,pl:mixin:APP:botania_xplat.mixins.json:AccessorRecipeManager,pl:mixin:APP:crafttweaker.mixins.json:common.access.recipe.AccessRecipeManager,pl:mixin:APP:farmersdelight.mixins.json:accessor.RecipeManagerAccessor,pl:mixin:A}
        at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10789_(SimplePreparableReloadListener.java:13) ~[server-1.18.2-20220404.173914-srg.jar%23420!/:?] {re:mixin,re:computing_frames,re:classloading}
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?] {}
        at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?] {}
        at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:69) ~[server-1.18.2-20220404.173914-srg.jar%23420!/:?] {re:classloading}
        at net.minecraft.server.packs.resources.SimpleReloadInstance.m_10834_(SimpleReloadInstance.java:68) ~[server-1.18.2-20220404.173914-srg.jar%23420!/:?] {re:classloading}
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) ~[?:?] {}
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?] {}
        at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?] {re:mixin}
        at java.util.concurrent.CompletableFuture.postFire(Unknown Source) ~[?:?] {re:mixin}
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?] {}
        at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?] {}
        at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:69) ~[server-1.18.2-20220404.173914-srg.jar%23420!/:?] {re:classloading}
        at net.minecraft.server.packs.resources.SimpleReloadInstance.m_10834_(SimpleReloadInstance.java:68) ~[server-1.18.2-20220404.173914-srg.jar%23420!/:?] {re:classloading}
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) ~[?:?] {}
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?] {}
        at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?] {re:mixin}
        at java.util.concurrent.CompletableFuture.postFire(Unknown Source) ~[?:?] {re:mixin}
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?] {}
        at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?] {}
        at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:69) ~[server-1.18.2-20220404.173914-srg.jar%23420!/:?] {re:classloading}
        at net.minecraft.server.packs.resources.SimpleReloadInstance.m_10834_(SimpleReloadInstance.java:68) ~[server-1.18.2-20220404.173914-srg.jar%23420!/:?] {re:classloading}
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) ~[?:?] {}
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?] {}
        at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?] {re:mixin}
        at java.util.concurrent.CompletableFuture.complete(Unknown Source) ~[?:?] {re:mixin}
        at net.minecraft.server.packs.resources.SimpleReloadInstance$1.m_10855_(SimpleReloadInstance.java:51) ~[server-1.18.2-20220404.173914-srg.jar%23420!/:?] {re:classloading}
        at net.minecraft.server.packs.resources.SimpleReloadInstance$1.m_6769_(SimpleReloadInstance.java:48) ~[server-1.18.2-20220404.173914-srg.jar%23420!/:?] {re:classloading}
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source) [?:?] {}
        at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) [?:?] {re:mixin}
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) [?:?] {}
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) [?:?] {}
        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:?] {}
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) [?:?] {}
        at java.util.concurrent.ForkJoinPool.scan(Unknown Source) [?:?] {re:computing_frames}
        at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:?] {re:computing_frames}
        at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:?] {}
/data/FeedTheBeast/start.sh: line 54:   354 Killed                  "$JAVA" ${1}

Exiting...

```
---
More details in latest.log
[latest.log](https://github.com/MKr4zy/Admate/files/9863638/latest.log)

**Comment by MKr4zy** [comment]
HAHA
Works on my end.
lul ged gud
safe dns^^
